#  Barrowcroft, 2024

#  A simple interface for SQLite3.

from typing import Any

class SQLI:
    def __init__(self) -> None: ...
    def database_open(self) -> bool: ...
    def database_valid(self, filename: str) -> bool: ...
    def create(self, database: str) -> bool: ...
    def open(self, database: str) -> bool: ...
    def close(self) -> bool: ...
    def execute_script(self, sql: str) -> None: ...
    def execute_sql(self, sql: str) -> list[Any]: ...
    def execute(self, sql: str) -> None: ...
    def script(self, parms: dict[str, str]) -> None: ...
    def tables(self, _: dict[str, str]) -> None: ...
    def indices(self, _: dict[str, str]) -> None: ...
    def views(self, _: dict[str, str]) -> None: ...
    def triggers(self, _: dict[str, str]) -> None: ...
    def schema(self, _: dict[str, str]) -> None: ...
    def describe(self, parms: dict[str, str]) -> None: ...
